import {
  AMBER_300,
  ROSE_600,
  SKY_200,
  SKY_500,
  SLATE_300,
  SLATE_500,
} from './tailwindColors';

export const TOOLBAR_ICON_COLOR = SLATE_300;
export const CANVAS_ICON_COLOR = SLATE_500;
export const CANVAS_SHAPE_EDGE_COLOR = ROSE_600;
export const CANVAS_SHAPE_NODE_STROKE_COLOR = ROSE_600;
export const CANVAS_SHAPE_UNSELECTED_NODE_FILL_COLOR = SKY_200;
export const CANVAS_SHAPE_SELECTED_NODE_FILL_COLOR = SKY_500;
export const CANVAS_SHAPE_PREVIEW_NODE_FILL_COLOR = AMBER_300;
